// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatecorrelation = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cross-level": {
            "get": {
                "description": "node 와 pod 와 direction 과 dimension 과 rank 필터 후 pagination 적용한 cross-level 시리즈 반환",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation"
                ],
                "summary": "List cross-level interference top-N",
                "parameters": [
                    {
                        "type": "string",
                        "description": "공유 node 이름 필터",
                        "name": "node",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pod 의 namespace 필터",
                        "name": "pod_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pod 이름 필터",
                        "name": "pod",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "방향 필터 (node_to_pod/pod_to_node)",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "리소스 차원 필터 (cpu/memory/network/gpu)",
                        "name": "dimension",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max rank (기본 무제한)",
                        "name": "rank_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 item 최대 개수 (기본 100, 최대 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 시작 offset (기본 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.CrossLevelListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cross-node-interference": {
            "get": {
                "description": "victim_node 와 suspect_node 와 dimension 과 rank 필터 후 pagination 적용한 cross-node interference 시리즈 반환",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation"
                ],
                "summary": "List cross-node interference top-N",
                "parameters": [
                    {
                        "type": "string",
                        "description": "victim node 이름 필터",
                        "name": "victim_node",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "suspect node 이름 필터",
                        "name": "suspect_node",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "리소스 차원 필터 (cpu/memory/network/gpu)",
                        "name": "dimension",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max rank (기본 무제한)",
                        "name": "rank_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 item 최대 개수 (기본 100, 최대 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 시작 offset (기본 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.CrossNodeListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/drops": {
            "get": {
                "description": "drop_reason 별 5-tuple 분포 조회. namespace 와 reason 필터 후 pagination 적용",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "netobs"
                ],
                "summary": "List packet drop events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "drop reason 필터",
                        "name": "drop_reason",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "drop category 필터",
                        "name": "drop_category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "src Pod 의 namespace 필터",
                        "name": "src_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "src Pod 의 이름 필터",
                        "name": "src_pod",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IP version 필터 (4 또는 6, #103 IPv6 확장)",
                        "name": "ip_version",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 item 최대 개수 (기본 100, 최대 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 시작 offset (기본 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DropListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_netobs_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/flows": {
            "get": {
                "description": "5-tuple 기준 flow bytes 와 rate 조회. namespace/pod/protocol/direction 필터 후 pagination 적용",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "netobs"
                ],
                "summary": "List Pod-to-Pod network flows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "src Pod 의 namespace 필터",
                        "name": "src_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "src Pod 의 이름 필터",
                        "name": "src_pod",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "dst Pod 의 namespace 필터",
                        "name": "dst_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "dst Pod 의 이름 필터",
                        "name": "dst_pod",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "프로토콜 필터 (tcp/udp)",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "방향 필터 (egress/ingress)",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IP version 필터 (4 또는 6, #103 IPv6 확장)",
                        "name": "ip_version",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 item 최대 개수 (기본 100, 최대 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 시작 offset (기본 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.FlowListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_netobs_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/gpu": {
            "get": {
                "description": "device scope 또는 pod scope 의 GPU utilization 과 memory 와 temperature 와 power 통합 조회",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gpuobs"
                ],
                "summary": "List GPU resource usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "scope (device 또는 pod, 기본 device)",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "node 필터",
                        "name": "node",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gpu_uuid 필터",
                        "name": "gpu_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pod 의 namespace 필터 (scope=pod 일 때만 유효)",
                        "name": "src_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pod 의 이름 필터 (scope=pod 일 때만 유효)",
                        "name": "src_pod",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 item 최대 개수 (기본 100, 최대 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 시작 offset (기본 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_gpuobs_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/impact-graph": {
            "get": {
                "description": "suspect → victim 1-hop 엣지로 구성된 영향 전파 그래프의 정점 (out/in degree 포함) 과 엣지 전체 반환",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation"
                ],
                "summary": "Get impact propagation graph",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.ImpactGraphResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/impact-paths": {
            "get": {
                "description": "근원 suspect(root)에서 종착 victim(terminal)으로 이어지는 다단계 경로와 근원 요약 반환. root_pod / terminal_pod / namespace / min_score 필터 지원",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation"
                ],
                "summary": "List multi-hop impact propagation paths",
                "parameters": [
                    {
                        "type": "string",
                        "description": "근원 suspect pod 이름 필터",
                        "name": "root_pod",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "종착 victim pod 이름 필터",
                        "name": "terminal_pod",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "root 또는 terminal 의 namespace 필터",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "경로 weakest-link score 하한 필터",
                        "name": "min_score",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.ImpactPathsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/noisy-neighbor": {
            "get": {
                "description": "victim/suspect 와 dimension 과 rank 필터 후 pagination 적용한 noisy neighbor 시리즈 반환",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation"
                ],
                "summary": "List noisy neighbor top-N",
                "parameters": [
                    {
                        "type": "string",
                        "description": "victim Pod 의 namespace 필터",
                        "name": "victim_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "victim Pod 의 이름 필터",
                        "name": "victim_pod",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "suspect Pod 의 namespace 필터",
                        "name": "suspect_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "suspect Pod 의 이름 필터",
                        "name": "suspect_pod",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "리소스 차원 필터 (cpu/memory/network/gpu)",
                        "name": "dimension",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "victim 영향 종착 차원 필터 (latency/throughput/error)",
                        "name": "victim_signal",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max rank (기본 무제한)",
                        "name": "rank_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 item 최대 개수 (기본 100, 최대 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 시작 offset (기본 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.NoisyNeighborListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/service-impact": {
            "get": {
                "description": "victim_namespace 와 victim_workload 와 suspect_node 와 dimension 과 rank 필터 후 pagination 적용한 service-impact 시리즈 반환",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation"
                ],
                "summary": "List service-impact top-N",
                "parameters": [
                    {
                        "type": "string",
                        "description": "victim workload 의 namespace 필터",
                        "name": "victim_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "victim workload (Service 근사) 이름 필터",
                        "name": "victim_workload",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "suspect node 이름 필터",
                        "name": "suspect_node",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "리소스 차원 필터 (cpu/memory/network/gpu)",
                        "name": "dimension",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max rank (기본 무제한)",
                        "name": "rank_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 item 최대 개수 (기본 100, 최대 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 시작 offset (기본 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.ServiceImpactListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_correlation_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.DropEntry": {
            "type": "object",
            "properties": {
                "drop_category": {
                    "type": "string"
                },
                "drop_reason": {
                    "type": "string"
                },
                "dst_ip": {
                    "type": "string"
                },
                "dst_port": {
                    "type": "integer"
                },
                "event_count": {
                    "type": "integer"
                },
                "events_per_sec": {
                    "type": "number"
                },
                "ip_version": {
                    "type": "string"
                },
                "node": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "src_ip": {
                    "type": "string"
                },
                "src_namespace": {
                    "type": "string"
                },
                "src_pod": {
                    "type": "string"
                },
                "src_port": {
                    "type": "integer"
                }
            }
        },
        "api.DropListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.DropEntry"
                    }
                },
                "page": {
                    "$ref": "#/definitions/internal_netobs_api.PageInfo"
                }
            }
        },
        "api.FlowEntry": {
            "type": "object",
            "properties": {
                "bytes_per_sec": {
                    "type": "number"
                },
                "bytes_total": {
                    "type": "integer"
                },
                "direction": {
                    "type": "string"
                },
                "dst_ip": {
                    "type": "string"
                },
                "dst_namespace": {
                    "type": "string"
                },
                "dst_pod": {
                    "type": "string"
                },
                "dst_port": {
                    "type": "integer"
                },
                "ip_version": {
                    "type": "string"
                },
                "node": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "src_ip": {
                    "type": "string"
                },
                "src_namespace": {
                    "type": "string"
                },
                "src_pod": {
                    "type": "string"
                },
                "src_port": {
                    "type": "integer"
                }
            }
        },
        "api.FlowListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.FlowEntry"
                    }
                },
                "page": {
                    "$ref": "#/definitions/internal_netobs_api.PageInfo"
                }
            }
        },
        "api.GPUEntry": {
            "type": "object",
            "properties": {
                "gpu_index": {
                    "type": "string"
                },
                "gpu_model": {
                    "type": "string"
                },
                "gpu_uuid": {
                    "type": "string"
                },
                "memory_total_bytes": {
                    "type": "integer"
                },
                "memory_used_bytes": {
                    "type": "integer"
                },
                "node": {
                    "type": "string"
                },
                "power_limit_watts": {
                    "type": "number"
                },
                "power_usage_watts": {
                    "type": "number"
                },
                "scope": {
                    "type": "string"
                },
                "src_namespace": {
                    "type": "string"
                },
                "src_pod": {
                    "type": "string"
                },
                "temperature_celsius": {
                    "type": "number"
                },
                "utilization_percent": {
                    "type": "number"
                }
            }
        },
        "api.GPUListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.GPUEntry"
                    }
                },
                "page": {
                    "$ref": "#/definitions/internal_gpuobs_api.PageInfo"
                }
            }
        },
        "internal_correlation_api.CrossLevelListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.CrossLevel"
                    }
                },
                "page": {
                    "$ref": "#/definitions/netobs_internal_apicommon.Page"
                }
            }
        },
        "internal_correlation_api.CrossNodeListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.NodeInterference"
                    }
                },
                "page": {
                    "$ref": "#/definitions/netobs_internal_apicommon.Page"
                }
            }
        },
        "internal_correlation_api.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_correlation_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_correlation_api.ErrorDetail"
                }
            }
        },
        "internal_correlation_api.ImpactGraphResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.ImpactGraphEdge"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.ImpactGraphNode"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/internal_correlation_api.ImpactGraphSummary"
                }
            }
        },
        "internal_correlation_api.ImpactGraphSummary": {
            "type": "object",
            "properties": {
                "edge_count": {
                    "type": "integer"
                },
                "node_count": {
                    "type": "integer"
                }
            }
        },
        "internal_correlation_api.ImpactPathsResponse": {
            "type": "object",
            "properties": {
                "paths": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.ImpactPath"
                    }
                },
                "roots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.RootSuspect"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/internal_correlation_api.ImpactPathsSummary"
                }
            }
        },
        "internal_correlation_api.ImpactPathsSummary": {
            "type": "object",
            "properties": {
                "path_count": {
                    "type": "integer"
                },
                "root_count": {
                    "type": "integer"
                }
            }
        },
        "internal_correlation_api.NoisyNeighborListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.NoisyNeighbor"
                    }
                },
                "page": {
                    "$ref": "#/definitions/netobs_internal_apicommon.Page"
                }
            }
        },
        "internal_correlation_api.ServiceImpactListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.ServiceImpact"
                    }
                },
                "page": {
                    "$ref": "#/definitions/netobs_internal_apicommon.Page"
                }
            }
        },
        "internal_gpuobs_api.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_gpuobs_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_gpuobs_api.ErrorDetail"
                }
            }
        },
        "internal_gpuobs_api.PageInfo": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_netobs_api.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_netobs_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_netobs_api.ErrorDetail"
                }
            }
        },
        "internal_netobs_api.PageInfo": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "netobs_internal_apicommon.Page": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "netobs_internal_correlation.CrossLevel": {
            "type": "object",
            "properties": {
                "dimension": {
                    "$ref": "#/definitions/netobs_internal_correlation.ResourceDimension"
                },
                "direction": {
                    "$ref": "#/definitions/netobs_internal_correlation.CrossLevelDirection"
                },
                "granger_ok": {
                    "type": "boolean"
                },
                "lag_steps": {
                    "type": "integer"
                },
                "node": {
                    "type": "string"
                },
                "p_value": {
                    "type": "number"
                },
                "pod": {
                    "type": "string"
                },
                "pod_namespace": {
                    "type": "string"
                },
                "pod_uid": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "sample_count": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "suspect_metric": {
                    "type": "string"
                },
                "victim_metric": {
                    "type": "string"
                }
            }
        },
        "netobs_internal_correlation.CrossLevelDirection": {
            "type": "string",
            "enum": [
                "node_to_pod",
                "pod_to_node"
            ],
            "x-enum-varnames": [
                "DirectionNodeToPod",
                "DirectionPodToNode"
            ]
        },
        "netobs_internal_correlation.ImpactGraphEdge": {
            "type": "object",
            "properties": {
                "dimension": {
                    "$ref": "#/definitions/netobs_internal_correlation.ResourceDimension"
                },
                "granger_ok": {
                    "type": "boolean"
                },
                "lag_steps": {
                    "type": "integer"
                },
                "p_value": {
                    "type": "number"
                },
                "score": {
                    "type": "number"
                },
                "suspect": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                },
                "victim": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                },
                "victim_signal": {
                    "$ref": "#/definitions/netobs_internal_correlation.VictimSignal"
                }
            }
        },
        "netobs_internal_correlation.ImpactGraphNode": {
            "type": "object",
            "properties": {
                "in_degree": {
                    "type": "integer"
                },
                "namespace": {
                    "type": "string"
                },
                "out_degree": {
                    "type": "integer"
                },
                "pod": {
                    "type": "string"
                },
                "pod_uid": {
                    "type": "string"
                }
            }
        },
        "netobs_internal_correlation.ImpactPath": {
            "type": "object",
            "properties": {
                "depth": {
                    "type": "integer"
                },
                "hops": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/netobs_internal_correlation.ImpactPathHop"
                    }
                },
                "root": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                },
                "root_kind": {
                    "$ref": "#/definitions/netobs_internal_correlation.RootKind"
                },
                "score": {
                    "type": "number"
                },
                "terminal": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                }
            }
        },
        "netobs_internal_correlation.ImpactPathHop": {
            "type": "object",
            "properties": {
                "dimension": {
                    "$ref": "#/definitions/netobs_internal_correlation.ResourceDimension"
                },
                "lag_steps": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "suspect": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                },
                "victim": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                },
                "victim_signal": {
                    "$ref": "#/definitions/netobs_internal_correlation.VictimSignal"
                }
            }
        },
        "netobs_internal_correlation.NodeInterference": {
            "type": "object",
            "properties": {
                "dimension": {
                    "$ref": "#/definitions/netobs_internal_correlation.ResourceDimension"
                },
                "granger_ok": {
                    "type": "boolean"
                },
                "lag_steps": {
                    "type": "integer"
                },
                "p_value": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                },
                "sample_count": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "suspect_metric": {
                    "type": "string"
                },
                "suspect_node": {
                    "type": "string"
                },
                "victim_metric": {
                    "type": "string"
                },
                "victim_node": {
                    "type": "string"
                }
            }
        },
        "netobs_internal_correlation.NoisyNeighbor": {
            "type": "object",
            "properties": {
                "dimension": {
                    "$ref": "#/definitions/netobs_internal_correlation.ResourceDimension"
                },
                "granger_ok": {
                    "type": "boolean"
                },
                "impact_ok": {
                    "type": "boolean"
                },
                "impact_seconds": {
                    "description": "#146 effect size 결과. Impact 는 suspect 압박 시 victim latency 증가량 (seconds) 으로 간섭의\n절대 영향 크기다. Score (상관 강도) 와 독립된 지표라 운영자가 우선순위 판단에 함께 활용한다.\nImpactOK=false 면 표본 부족 등으로 산정이 skip 되어 Impact 는 0 이다.",
                    "type": "number"
                },
                "lag_steps": {
                    "type": "integer"
                },
                "p_value": {
                    "description": "#69 Granger causality 결과. PValue 는 src 가 dst 를 Granger-cause 하는지의 통계적 유의성.\nGrangerOK=false 면 표본 부족 또는 행렬 singular 로 산정이 자연 skip 되었다.",
                    "type": "number"
                },
                "rank": {
                    "description": "Rank 는 (victim, victim_signal, dimension) 그룹 내 max_abs_value 내림차순 1-based 순위다. 1 이 가장 강한 상관.",
                    "type": "integer"
                },
                "sample_count": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "suspect": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                },
                "suspect_metric": {
                    "type": "string"
                },
                "victim": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                },
                "victim_metric": {
                    "type": "string"
                },
                "victim_signal": {
                    "description": "VictimSignal 은 #150 의 victim 영향 종착 차원 (latency / throughput / error) 이다. dimension 이\nsuspect 의 자원 종류라면 VictimSignal 은 victim 측 품질 저하의 종류다. Top-N 은 (victim, victim_\nsignal, dimension) 그룹별로 산정되어 한 victim 이 신호별로 독립 순위를 갖는다.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/netobs_internal_correlation.VictimSignal"
                        }
                    ]
                }
            }
        },
        "netobs_internal_correlation.PodIdentity": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                },
                "pod": {
                    "type": "string"
                },
                "pod_uid": {
                    "type": "string"
                }
            }
        },
        "netobs_internal_correlation.ResourceDimension": {
            "type": "string",
            "enum": [
                "cpu",
                "memory",
                "network",
                "gpu",
                ""
            ],
            "x-enum-varnames": [
                "DimensionCPU",
                "DimensionMemory",
                "DimensionNetwork",
                "DimensionGPU",
                "DimensionUnknown"
            ]
        },
        "netobs_internal_correlation.RootKind": {
            "type": "string",
            "enum": [
                "source",
                "net_source"
            ],
            "x-enum-varnames": [
                "RootKindSource",
                "RootKindNetSource"
            ]
        },
        "netobs_internal_correlation.RootSuspect": {
            "type": "object",
            "properties": {
                "kind": {
                    "$ref": "#/definitions/netobs_internal_correlation.RootKind"
                },
                "path_count": {
                    "type": "integer"
                },
                "reach": {
                    "type": "integer"
                },
                "root": {
                    "$ref": "#/definitions/netobs_internal_correlation.PodIdentity"
                }
            }
        },
        "netobs_internal_correlation.ServiceImpact": {
            "type": "object",
            "properties": {
                "dimension": {
                    "$ref": "#/definitions/netobs_internal_correlation.ResourceDimension"
                },
                "granger_ok": {
                    "type": "boolean"
                },
                "lag_steps": {
                    "type": "integer"
                },
                "p_value": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                },
                "sample_count": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "suspect_metric": {
                    "type": "string"
                },
                "suspect_node": {
                    "type": "string"
                },
                "victim_metric": {
                    "type": "string"
                },
                "victim_namespace": {
                    "type": "string"
                },
                "victim_workload": {
                    "type": "string"
                }
            }
        },
        "netobs_internal_correlation.VictimSignal": {
            "type": "string",
            "enum": [
                "latency",
                "throughput",
                "error",
                ""
            ],
            "x-enum-varnames": [
                "SignalLatency",
                "SignalThroughput",
                "SignalError",
                "SignalNone"
            ]
        }
    }
}`

// SwaggerInfocorrelation holds exported Swagger Info so clients can modify it
var SwaggerInfocorrelation = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "correlation",
	SwaggerTemplate:  docTemplatecorrelation,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfocorrelation.InstanceName(), SwaggerInfocorrelation)
}
