// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && nccl

package nccl

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type NcclUprobeNcclStartKey struct {
	Tid uint32
	Op  uint8
	Pad [3]uint8
}

// LoadNcclUprobe returns the embedded CollectionSpec for NcclUprobe.
func LoadNcclUprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NcclUprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NcclUprobe: %w", err)
	}

	return spec, err
}

// LoadNcclUprobeObjects loads NcclUprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NcclUprobeObjects
//	*NcclUprobePrograms
//	*NcclUprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNcclUprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNcclUprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NcclUprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NcclUprobeSpecs struct {
	NcclUprobeProgramSpecs
	NcclUprobeMapSpecs
	NcclUprobeVariableSpecs
}

// NcclUprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NcclUprobeProgramSpecs struct {
	HandleNcclAllgatherEntry     *ebpf.ProgramSpec `ebpf:"handle_nccl_allgather_entry"`
	HandleNcclAllgatherExit      *ebpf.ProgramSpec `ebpf:"handle_nccl_allgather_exit"`
	HandleNcclAllreduceEntry     *ebpf.ProgramSpec `ebpf:"handle_nccl_allreduce_entry"`
	HandleNcclAllreduceExit      *ebpf.ProgramSpec `ebpf:"handle_nccl_allreduce_exit"`
	HandleNcclBroadcastEntry     *ebpf.ProgramSpec `ebpf:"handle_nccl_broadcast_entry"`
	HandleNcclBroadcastExit      *ebpf.ProgramSpec `ebpf:"handle_nccl_broadcast_exit"`
	HandleNcclReducescatterEntry *ebpf.ProgramSpec `ebpf:"handle_nccl_reducescatter_entry"`
	HandleNcclReducescatterExit  *ebpf.ProgramSpec `ebpf:"handle_nccl_reducescatter_exit"`
}

// NcclUprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NcclUprobeMapSpecs struct {
	NcclDropped *ebpf.MapSpec `ebpf:"nccl_dropped"`
	NcclEvents  *ebpf.MapSpec `ebpf:"nccl_events"`
	NcclStarts  *ebpf.MapSpec `ebpf:"nccl_starts"`
}

// NcclUprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NcclUprobeVariableSpecs struct {
}

// NcclUprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNcclUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type NcclUprobeObjects struct {
	NcclUprobePrograms
	NcclUprobeMaps
	NcclUprobeVariables
}

func (o *NcclUprobeObjects) Close() error {
	return _NcclUprobeClose(
		&o.NcclUprobePrograms,
		&o.NcclUprobeMaps,
	)
}

// NcclUprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNcclUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type NcclUprobeMaps struct {
	NcclDropped *ebpf.Map `ebpf:"nccl_dropped"`
	NcclEvents  *ebpf.Map `ebpf:"nccl_events"`
	NcclStarts  *ebpf.Map `ebpf:"nccl_starts"`
}

func (m *NcclUprobeMaps) Close() error {
	return _NcclUprobeClose(
		m.NcclDropped,
		m.NcclEvents,
		m.NcclStarts,
	)
}

// NcclUprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNcclUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type NcclUprobeVariables struct {
}

// NcclUprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNcclUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type NcclUprobePrograms struct {
	HandleNcclAllgatherEntry     *ebpf.Program `ebpf:"handle_nccl_allgather_entry"`
	HandleNcclAllgatherExit      *ebpf.Program `ebpf:"handle_nccl_allgather_exit"`
	HandleNcclAllreduceEntry     *ebpf.Program `ebpf:"handle_nccl_allreduce_entry"`
	HandleNcclAllreduceExit      *ebpf.Program `ebpf:"handle_nccl_allreduce_exit"`
	HandleNcclBroadcastEntry     *ebpf.Program `ebpf:"handle_nccl_broadcast_entry"`
	HandleNcclBroadcastExit      *ebpf.Program `ebpf:"handle_nccl_broadcast_exit"`
	HandleNcclReducescatterEntry *ebpf.Program `ebpf:"handle_nccl_reducescatter_entry"`
	HandleNcclReducescatterExit  *ebpf.Program `ebpf:"handle_nccl_reducescatter_exit"`
}

func (p *NcclUprobePrograms) Close() error {
	return _NcclUprobeClose(
		p.HandleNcclAllgatherEntry,
		p.HandleNcclAllgatherExit,
		p.HandleNcclAllreduceEntry,
		p.HandleNcclAllreduceExit,
		p.HandleNcclBroadcastEntry,
		p.HandleNcclBroadcastExit,
		p.HandleNcclReducescatterEntry,
		p.HandleNcclReducescatterExit,
	)
}

func _NcclUprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nccluprobe_bpfeb.o
var _NcclUprobeBytes []byte
