// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpfx

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type NetObsNetobsConnectStash struct {
	Ts   uint64
	Pid  uint32
	Tid  uint32
	Comm [16]int8
}

type NetObsNetobsFlowKey struct {
	CgroupId  uint64
	Saddr     [16]uint8
	Daddr     [16]uint8
	Sport     uint16
	Dport     uint16
	Protocol  uint8
	Direction uint8
	Family    uint8
	Pad       uint8
}

type NetObsNetobsFlowValue struct{ Bytes uint64 }

type NetObsNetobsNicIngress struct {
	TsNic uint64
	TsL3  uint64
	Skb   uint64
}

type NetObsNetobsPodBytesKey struct {
	CgroupId  uint64
	Direction uint8
	Layer     uint8
	Pad       [6]uint8
}

type NetObsNetobsPodBytesValue struct {
	Bytes   uint64
	Packets uint64
}

type NetObsNetobsRecvState struct {
	TsL3          uint64
	TsEstablished uint64
	TsData        uint64
}

type NetObsNetobsSegAccum struct {
	FirstTs             uint64
	CumulativeLatencyNs uint64
	SegmentCount        uint32
	Pad                 [4]uint8
}

type NetObsNetobsStartInfo struct {
	TsNs           uint64
	CgroupId       uint64
	SocketCookie   uint64
	Saddr          [16]uint8
	Daddr          [16]uint8
	Pid            uint32
	Tid            uint32
	Ifindex        uint32
	SkbIif         uint32
	Sport          uint16
	Dport          uint16
	Comm           [16]int8
	SeenVeth       uint8
	SeenDevq       uint8
	RetSeen        uint8
	Protocol       uint8
	SndCwnd        uint32
	SrttUs         uint32
	SndSsthresh    uint32
	PadAlign       [4]uint8
	TsWriteXmit    uint64
	TsTransmitSkb  uint64
	TsSegmentEntry uint64
	SeenWriteXmit  uint8
	SeenTransmit   uint8
	Family         uint8
	Pad82          [5]uint8
}

// LoadNetObs returns the embedded CollectionSpec for NetObs.
func LoadNetObs() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetObsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetObs: %w", err)
	}

	return spec, err
}

// LoadNetObsObjects loads NetObs and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetObsObjects
//	*NetObsPrograms
//	*NetObsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetObsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetObs()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetObsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetObsSpecs struct {
	NetObsProgramSpecs
	NetObsMapSpecs
	NetObsVariableSpecs
}

// NetObsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetObsProgramSpecs struct {
	HandleDevQueueXmit      *ebpf.ProgramSpec `ebpf:"handle_dev_queue_xmit"`
	HandleKfreeSkbReason    *ebpf.ProgramSpec `ebpf:"handle_kfree_skb_reason"`
	HandleNetifReceiveSkb   *ebpf.ProgramSpec `ebpf:"handle_netif_receive_skb"`
	HandleTcpCleanupRbuf    *ebpf.ProgramSpec `ebpf:"handle_tcp_cleanup_rbuf"`
	HandleTcpFinishConnect  *ebpf.ProgramSpec `ebpf:"handle_tcp_finish_connect"`
	HandleTcpRcvEstablished *ebpf.ProgramSpec `ebpf:"handle_tcp_rcv_established"`
	HandleTcpRecvmsg        *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg"`
	HandleTcpRetransmitSkb  *ebpf.ProgramSpec `ebpf:"handle_tcp_retransmit_skb"`
	HandleTcpSendAck        *ebpf.ProgramSpec `ebpf:"handle_tcp_send_ack"`
	HandleTcpSendmsg        *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg"`
	HandleTcpSendmsgRet     *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg_ret"`
	HandleTcpTransmitSkb    *ebpf.ProgramSpec `ebpf:"handle_tcp_transmit_skb"`
	HandleTcpTransmitSkbRet *ebpf.ProgramSpec `ebpf:"handle_tcp_transmit_skb_ret"`
	HandleTcpV4Connect      *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV4DoRcv        *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_do_rcv"`
	HandleTcpV4Rcv          *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_rcv"`
	HandleTcpV6Connect      *ebpf.ProgramSpec `ebpf:"handle_tcp_v6_connect"`
	HandleTcpV6DoRcv        *ebpf.ProgramSpec `ebpf:"handle_tcp_v6_do_rcv"`
	HandleTcpV6Rcv          *ebpf.ProgramSpec `ebpf:"handle_tcp_v6_rcv"`
	HandleTcpWriteXmit      *ebpf.ProgramSpec `ebpf:"handle_tcp_write_xmit"`
	HandleTcpWriteXmitRet   *ebpf.ProgramSpec `ebpf:"handle_tcp_write_xmit_ret"`
	HandleUdpRecvmsg        *ebpf.ProgramSpec `ebpf:"handle_udp_recvmsg"`
	HandleUdpSendmsg        *ebpf.ProgramSpec `ebpf:"handle_udp_sendmsg"`
	HandleUdpv6Recvmsg      *ebpf.ProgramSpec `ebpf:"handle_udpv6_recvmsg"`
	HandleUdpv6Sendmsg      *ebpf.ProgramSpec `ebpf:"handle_udpv6_sendmsg"`
	HandleVethXmit          *ebpf.ProgramSpec `ebpf:"handle_veth_xmit"`
}

// NetObsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetObsMapSpecs struct {
	ConnectStarts *ebpf.MapSpec `ebpf:"connect_starts"`
	DropStacks    *ebpf.MapSpec `ebpf:"drop_stacks"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	EventsDropped *ebpf.MapSpec `ebpf:"events_dropped"`
	FlowBytes     *ebpf.MapSpec `ebpf:"flow_bytes"`
	NicIngress    *ebpf.MapSpec `ebpf:"nic_ingress"`
	PodBytes      *ebpf.MapSpec `ebpf:"pod_bytes"`
	RecvStarts    *ebpf.MapSpec `ebpf:"recv_starts"`
	SegAccum      *ebpf.MapSpec `ebpf:"seg_accum"`
	Starts        *ebpf.MapSpec `ebpf:"starts"`
	TargetDaddr   *ebpf.MapSpec `ebpf:"target_daddr"`
}

// NetObsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetObsVariableSpecs struct {
}

// NetObsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetObsObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetObsObjects struct {
	NetObsPrograms
	NetObsMaps
	NetObsVariables
}

func (o *NetObsObjects) Close() error {
	return _NetObsClose(
		&o.NetObsPrograms,
		&o.NetObsMaps,
	)
}

// NetObsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetObsObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetObsMaps struct {
	ConnectStarts *ebpf.Map `ebpf:"connect_starts"`
	DropStacks    *ebpf.Map `ebpf:"drop_stacks"`
	Events        *ebpf.Map `ebpf:"events"`
	EventsDropped *ebpf.Map `ebpf:"events_dropped"`
	FlowBytes     *ebpf.Map `ebpf:"flow_bytes"`
	NicIngress    *ebpf.Map `ebpf:"nic_ingress"`
	PodBytes      *ebpf.Map `ebpf:"pod_bytes"`
	RecvStarts    *ebpf.Map `ebpf:"recv_starts"`
	SegAccum      *ebpf.Map `ebpf:"seg_accum"`
	Starts        *ebpf.Map `ebpf:"starts"`
	TargetDaddr   *ebpf.Map `ebpf:"target_daddr"`
}

func (m *NetObsMaps) Close() error {
	return _NetObsClose(
		m.ConnectStarts,
		m.DropStacks,
		m.Events,
		m.EventsDropped,
		m.FlowBytes,
		m.NicIngress,
		m.PodBytes,
		m.RecvStarts,
		m.SegAccum,
		m.Starts,
		m.TargetDaddr,
	)
}

// NetObsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetObsObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetObsVariables struct {
}

// NetObsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetObsObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetObsPrograms struct {
	HandleDevQueueXmit      *ebpf.Program `ebpf:"handle_dev_queue_xmit"`
	HandleKfreeSkbReason    *ebpf.Program `ebpf:"handle_kfree_skb_reason"`
	HandleNetifReceiveSkb   *ebpf.Program `ebpf:"handle_netif_receive_skb"`
	HandleTcpCleanupRbuf    *ebpf.Program `ebpf:"handle_tcp_cleanup_rbuf"`
	HandleTcpFinishConnect  *ebpf.Program `ebpf:"handle_tcp_finish_connect"`
	HandleTcpRcvEstablished *ebpf.Program `ebpf:"handle_tcp_rcv_established"`
	HandleTcpRecvmsg        *ebpf.Program `ebpf:"handle_tcp_recvmsg"`
	HandleTcpRetransmitSkb  *ebpf.Program `ebpf:"handle_tcp_retransmit_skb"`
	HandleTcpSendAck        *ebpf.Program `ebpf:"handle_tcp_send_ack"`
	HandleTcpSendmsg        *ebpf.Program `ebpf:"handle_tcp_sendmsg"`
	HandleTcpSendmsgRet     *ebpf.Program `ebpf:"handle_tcp_sendmsg_ret"`
	HandleTcpTransmitSkb    *ebpf.Program `ebpf:"handle_tcp_transmit_skb"`
	HandleTcpTransmitSkbRet *ebpf.Program `ebpf:"handle_tcp_transmit_skb_ret"`
	HandleTcpV4Connect      *ebpf.Program `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV4DoRcv        *ebpf.Program `ebpf:"handle_tcp_v4_do_rcv"`
	HandleTcpV4Rcv          *ebpf.Program `ebpf:"handle_tcp_v4_rcv"`
	HandleTcpV6Connect      *ebpf.Program `ebpf:"handle_tcp_v6_connect"`
	HandleTcpV6DoRcv        *ebpf.Program `ebpf:"handle_tcp_v6_do_rcv"`
	HandleTcpV6Rcv          *ebpf.Program `ebpf:"handle_tcp_v6_rcv"`
	HandleTcpWriteXmit      *ebpf.Program `ebpf:"handle_tcp_write_xmit"`
	HandleTcpWriteXmitRet   *ebpf.Program `ebpf:"handle_tcp_write_xmit_ret"`
	HandleUdpRecvmsg        *ebpf.Program `ebpf:"handle_udp_recvmsg"`
	HandleUdpSendmsg        *ebpf.Program `ebpf:"handle_udp_sendmsg"`
	HandleUdpv6Recvmsg      *ebpf.Program `ebpf:"handle_udpv6_recvmsg"`
	HandleUdpv6Sendmsg      *ebpf.Program `ebpf:"handle_udpv6_sendmsg"`
	HandleVethXmit          *ebpf.Program `ebpf:"handle_veth_xmit"`
}

func (p *NetObsPrograms) Close() error {
	return _NetObsClose(
		p.HandleDevQueueXmit,
		p.HandleKfreeSkbReason,
		p.HandleNetifReceiveSkb,
		p.HandleTcpCleanupRbuf,
		p.HandleTcpFinishConnect,
		p.HandleTcpRcvEstablished,
		p.HandleTcpRecvmsg,
		p.HandleTcpRetransmitSkb,
		p.HandleTcpSendAck,
		p.HandleTcpSendmsg,
		p.HandleTcpSendmsgRet,
		p.HandleTcpTransmitSkb,
		p.HandleTcpTransmitSkbRet,
		p.HandleTcpV4Connect,
		p.HandleTcpV4DoRcv,
		p.HandleTcpV4Rcv,
		p.HandleTcpV6Connect,
		p.HandleTcpV6DoRcv,
		p.HandleTcpV6Rcv,
		p.HandleTcpWriteXmit,
		p.HandleTcpWriteXmitRet,
		p.HandleUdpRecvmsg,
		p.HandleUdpSendmsg,
		p.HandleUdpv6Recvmsg,
		p.HandleUdpv6Sendmsg,
		p.HandleVethXmit,
	)
}

func _NetObsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netobs_bpfeb.o
var _NetObsBytes []byte
