apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ebpf-project

resources:
  - ../../base

images:
  - name: netobs-agent
    newTag: "0.1.3"

patches:
  - path: patch-daemonset.yaml
