apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobs-agent
  namespace: ebpf-project
spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia
        observability.netobs/canary: "true"
      containers:
        - name: netobs-agent
          imagePullPolicy: Never
