apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netobs-agent
  namespace: ebpf-project
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: netobs-agent
    app.kubernetes.io/part-of: ebpf-project
spec:
  namespaceSelector:
    matchNames:
      - ebpf-project
  selector:
    matchLabels:
      app.kubernetes.io/name: netobs-agent
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
