apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpuobs-agent
  namespace: ebpf-project
  labels:
    app.kubernetes.io/name: gpuobs-agent
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: gpu-observer
imagePullSecrets:
  - name: ghcr-creds