apiVersion: v1
kind: Service
metadata:
  name: gpuobs-agent
  namespace: ebpf-project
  labels:
    app.kubernetes.io/name: gpuobs-agent
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: gpu-observer
spec:
  selector:
    app.kubernetes.io/name: gpuobs-agent
  ports:
    - name: metrics
      port: 9820
      targetPort: metrics
      protocol: TCP
