apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netobs-agent
  labels:
    app.kubernetes.io/name: netobs-agent
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: network-observer
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
