apiVersion: v1
kind: Namespace
metadata:
  name: ebpf-project
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    app.kubernetes.io/part-of: ebpf-project
