apiVersion: v1
kind: ServiceAccount
metadata:
  name: netobs-agent
  namespace: ebpf-project
  labels:
    app.kubernetes.io/name: netobs-agent
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: network-observer
imagePullSecrets:
  - name: ghcr-creds
