//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The netobs Authors.
// This file is auto-generated by controller-gen. DO NOT EDIT MANUALLY.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadScenario) DeepCopyInto(out *LoadScenario) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadScenario.
func (in *LoadScenario) DeepCopy() *LoadScenario {
	if in == nil {
		return nil
	}
	out := new(LoadScenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadScenario) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadScenarioList) DeepCopyInto(out *LoadScenarioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadScenario, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadScenarioList.
func (in *LoadScenarioList) DeepCopy() *LoadScenarioList {
	if in == nil {
		return nil
	}
	out := new(LoadScenarioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadScenarioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadScenarioSpec) DeepCopyInto(out *LoadScenarioSpec) {
	*out = *in
	out.Duration = in.Duration
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadScenarioSpec.
func (in *LoadScenarioSpec) DeepCopy() *LoadScenarioSpec {
	if in == nil {
		return nil
	}
	out := new(LoadScenarioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadScenarioStatus) DeepCopyInto(out *LoadScenarioStatus) {
	*out = *in
	if in.RunStartTime != nil {
		in, out := &in.RunStartTime, &out.RunStartTime
		*out = (*in).DeepCopy()
	}
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulRunTime != nil {
		in, out := &in.LastSuccessfulRunTime, &out.LastSuccessfulRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastObservedSpikeAlerts != nil {
		in, out := &in.LastObservedSpikeAlerts, &out.LastObservedSpikeAlerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadScenarioStatus.
func (in *LoadScenarioStatus) DeepCopy() *LoadScenarioStatus {
	if in == nil {
		return nil
	}
	out := new(LoadScenarioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadScenarioTargetRef) DeepCopyInto(out *LoadScenarioTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadScenarioTargetRef.
func (in *LoadScenarioTargetRef) DeepCopy() *LoadScenarioTargetRef {
	if in == nil {
		return nil
	}
	out := new(LoadScenarioTargetRef)
	in.DeepCopyInto(out)
	return out
}
