// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplategpuobs = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/gpu": {
            "get": {
                "description": "device scope 또는 pod scope 의 GPU utilization 과 memory 와 temperature 와 power 통합 조회",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gpuobs"
                ],
                "summary": "List GPU resource usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "scope (device 또는 pod, 기본 device)",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "node 필터",
                        "name": "node",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gpu_uuid 필터",
                        "name": "gpu_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pod 의 namespace 필터 (scope=pod 일 때만 유효)",
                        "name": "src_namespace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pod 의 이름 필터 (scope=pod 일 때만 유효)",
                        "name": "src_pod",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 item 최대 개수 (기본 100, 최대 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "응답 시작 offset (기본 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GPUListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.ErrorDetail"
                }
            }
        },
        "api.GPUEntry": {
            "type": "object",
            "properties": {
                "gpu_index": {
                    "type": "string"
                },
                "gpu_model": {
                    "type": "string"
                },
                "gpu_uuid": {
                    "type": "string"
                },
                "memory_total_bytes": {
                    "type": "integer"
                },
                "memory_used_bytes": {
                    "type": "integer"
                },
                "node": {
                    "type": "string"
                },
                "power_limit_watts": {
                    "type": "number"
                },
                "power_usage_watts": {
                    "type": "number"
                },
                "scope": {
                    "type": "string"
                },
                "src_namespace": {
                    "type": "string"
                },
                "src_pod": {
                    "type": "string"
                },
                "temperature_celsius": {
                    "type": "number"
                },
                "utilization_percent": {
                    "type": "number"
                }
            }
        },
        "api.GPUListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.GPUEntry"
                    }
                },
                "page": {
                    "$ref": "#/definitions/api.PageInfo"
                }
            }
        },
        "api.PageInfo": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfogpuobs holds exported Swagger Info so clients can modify it
var SwaggerInfogpuobs = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "gpuobs",
	SwaggerTemplate:  docTemplategpuobs,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfogpuobs.InstanceName(), SwaggerInfogpuobs)
}
