// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package cuda

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadCudaUprobe returns the embedded CollectionSpec for CudaUprobe.
func LoadCudaUprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CudaUprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CudaUprobe: %w", err)
	}

	return spec, err
}

// LoadCudaUprobeObjects loads CudaUprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CudaUprobeObjects
//	*CudaUprobePrograms
//	*CudaUprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCudaUprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCudaUprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CudaUprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CudaUprobeSpecs struct {
	CudaUprobeProgramSpecs
	CudaUprobeMapSpecs
	CudaUprobeVariableSpecs
}

// CudaUprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CudaUprobeProgramSpecs struct {
	HandleCuLaunchCooperativeKernel *ebpf.ProgramSpec `ebpf:"handle_cu_launch_cooperative_kernel"`
	HandleCuLaunchKernel            *ebpf.ProgramSpec `ebpf:"handle_cu_launch_kernel"`
	HandleCuLaunchKernelEx          *ebpf.ProgramSpec `ebpf:"handle_cu_launch_kernel_ex"`
	HandleCuMemcpy                  *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy"`
	HandleCuMemcpy2d                *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_2d"`
	HandleCuMemcpy2dAsync           *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_2d_async"`
	HandleCuMemcpy3d                *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_3d"`
	HandleCuMemcpy3dAsync           *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_3d_async"`
	HandleCuMemcpyDtod              *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_dtod"`
	HandleCuMemcpyDtodAsync         *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_dtod_async"`
	HandleCuMemcpyDtoh              *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_dtoh"`
	HandleCuMemcpyDtohAsync         *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_dtoh_async"`
	HandleCuMemcpyHtod              *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_htod"`
	HandleCuMemcpyHtodAsync         *ebpf.ProgramSpec `ebpf:"handle_cu_memcpy_htod_async"`
}

// CudaUprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CudaUprobeMapSpecs struct {
	CudaDropped *ebpf.MapSpec `ebpf:"cuda_dropped"`
	CudaEvents  *ebpf.MapSpec `ebpf:"cuda_events"`
}

// CudaUprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CudaUprobeVariableSpecs struct {
}

// CudaUprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCudaUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type CudaUprobeObjects struct {
	CudaUprobePrograms
	CudaUprobeMaps
	CudaUprobeVariables
}

func (o *CudaUprobeObjects) Close() error {
	return _CudaUprobeClose(
		&o.CudaUprobePrograms,
		&o.CudaUprobeMaps,
	)
}

// CudaUprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCudaUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type CudaUprobeMaps struct {
	CudaDropped *ebpf.Map `ebpf:"cuda_dropped"`
	CudaEvents  *ebpf.Map `ebpf:"cuda_events"`
}

func (m *CudaUprobeMaps) Close() error {
	return _CudaUprobeClose(
		m.CudaDropped,
		m.CudaEvents,
	)
}

// CudaUprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCudaUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type CudaUprobeVariables struct {
}

// CudaUprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCudaUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type CudaUprobePrograms struct {
	HandleCuLaunchCooperativeKernel *ebpf.Program `ebpf:"handle_cu_launch_cooperative_kernel"`
	HandleCuLaunchKernel            *ebpf.Program `ebpf:"handle_cu_launch_kernel"`
	HandleCuLaunchKernelEx          *ebpf.Program `ebpf:"handle_cu_launch_kernel_ex"`
	HandleCuMemcpy                  *ebpf.Program `ebpf:"handle_cu_memcpy"`
	HandleCuMemcpy2d                *ebpf.Program `ebpf:"handle_cu_memcpy_2d"`
	HandleCuMemcpy2dAsync           *ebpf.Program `ebpf:"handle_cu_memcpy_2d_async"`
	HandleCuMemcpy3d                *ebpf.Program `ebpf:"handle_cu_memcpy_3d"`
	HandleCuMemcpy3dAsync           *ebpf.Program `ebpf:"handle_cu_memcpy_3d_async"`
	HandleCuMemcpyDtod              *ebpf.Program `ebpf:"handle_cu_memcpy_dtod"`
	HandleCuMemcpyDtodAsync         *ebpf.Program `ebpf:"handle_cu_memcpy_dtod_async"`
	HandleCuMemcpyDtoh              *ebpf.Program `ebpf:"handle_cu_memcpy_dtoh"`
	HandleCuMemcpyDtohAsync         *ebpf.Program `ebpf:"handle_cu_memcpy_dtoh_async"`
	HandleCuMemcpyHtod              *ebpf.Program `ebpf:"handle_cu_memcpy_htod"`
	HandleCuMemcpyHtodAsync         *ebpf.Program `ebpf:"handle_cu_memcpy_htod_async"`
}

func (p *CudaUprobePrograms) Close() error {
	return _CudaUprobeClose(
		p.HandleCuLaunchCooperativeKernel,
		p.HandleCuLaunchKernel,
		p.HandleCuLaunchKernelEx,
		p.HandleCuMemcpy,
		p.HandleCuMemcpy2d,
		p.HandleCuMemcpy2dAsync,
		p.HandleCuMemcpy3d,
		p.HandleCuMemcpy3dAsync,
		p.HandleCuMemcpyDtod,
		p.HandleCuMemcpyDtodAsync,
		p.HandleCuMemcpyDtoh,
		p.HandleCuMemcpyDtohAsync,
		p.HandleCuMemcpyHtod,
		p.HandleCuMemcpyHtodAsync,
	)
}

func _CudaUprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cudauprobe_bpfeb.o
var _CudaUprobeBytes []byte
