apiVersion: v1
kind: Service
metadata:
  name: rca-summarizer
  namespace: ebpf-project
  labels:
    app.kubernetes.io/name: rca-summarizer
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: rca-summarizer
spec:
  selector:
    app.kubernetes.io/name: rca-summarizer
  ports:
    - name: metrics
      port: 9850
      targetPort: metrics
      protocol: TCP
