apiVersion: v1
kind: ServiceAccount
metadata:
  name: rca-summarizer
  namespace: ebpf-project
  labels:
    app.kubernetes.io/name: rca-summarizer
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: rca-summarizer
imagePullSecrets:
  - name: ghcr-creds
