apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-injector
  namespace: ebpf-project
  labels:
    app.kubernetes.io/name: workload-injector
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: load-injector
imagePullSecrets:
  - name: ghcr-creds
