apiVersion: v1
kind: ServiceAccount
metadata:
  name: correlation-exporter
  namespace: ebpf-project
  labels:
    app.kubernetes.io/name: correlation-exporter
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: correlation-exporter
imagePullSecrets:
  - name: ghcr-creds
