apiVersion: v1
kind: Service
metadata:
  name: correlation-exporter
  namespace: ebpf-project
  labels:
    app.kubernetes.io/name: correlation-exporter
    app.kubernetes.io/part-of: ebpf-project
    app.kubernetes.io/component: correlation-exporter
spec:
  selector:
    app.kubernetes.io/name: correlation-exporter
  ports:
    - name: metrics
      port: 9830
      targetPort: metrics
      protocol: TCP
